In [1]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
#dtype
np.array([1,2,3],dtype=float)



array([1., 2., 3.])

In [9]:
np.array([4,5,6],dtype=complex)


array([4.+0.j, 5.+0.j, 6.+0.j])

In [10]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.arange(1,13).reshape(5,5) #got error

ValueError: cannot reshape array of size 12 into shape (5,5)

In [14]:
#np.ones and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.random.random((3,4))

array([[0.2783626 , 0.85381924, 0.25938846, 0.82514902],
       [0.64696749, 0.25121576, 0.68382238, 0.62510974],
       [0.41559757, 0.55301497, 0.88436123, 0.01603327]])

In [15]:
#np.linspace
np.linspace(-10,10,10)



array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Array attributes

In [19]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
# ndim
a3.ndim

3

In [23]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [25]:
# itemsize
a3.itemsize

8

In [26]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
Changong datatype

In [27]:
#astype
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
#scalar opeartions
#arthmetic
a1**2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [51]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
#vector operations
#arthmetic
a1**a2


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [37]:

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[28., 39.,  6.],
       [12.,  4., 36.],
       [51., 51., 24.]])

In [89]:
#max/min/sum/prod
np.max(a1)

np.int64(9)

In [90]:
np.min(a1)

np.int64(0)

In [91]:
np.sum(a1)

np.int64(45)

In [92]:
np.prod(a1)

np.int64(0)

In [93]:
## max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=0)

np.int64(9)

In [100]:
np.prod(a1,axis=0)

np.int64(0)

In [95]:
#mean/median/std/var
np.mean(a1)

np.float64(4.5)

In [96]:
np.var(a1)

np.float64(8.25)

In [62]:
#trigno function
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [63]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
a3


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [66]:
np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [67]:
#log and exponenets
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [74]:
#round/float/ceil
np.random.random((2,3))*100

array([[ 0.89328173, 67.84624657, 22.67979633],
       [ 4.99985402, 22.04503135, 93.12300171]])

In [75]:
np.round(np.random.random((2,3))*100)

array([[ 4., 38., 90.],
       [49., 53., 77.]])

In [78]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
a1[-1]


np.int64(9)

In [88]:
a2[1,3] #row and col

np.int64(7)

In [101]:
a3[1,0,1]

np.int64(5)

In [102]:
a3[0,1,1]

np.int64(3)

In [103]:
a3[0,0,0]

np.int64(0)

In [104]:
a3[1,1,0]

np.int64(6)

In [105]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
a1[2:5]

array([2, 3, 4])

In [108]:
a1[2:5:2]

array([2, 4])

In [109]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a2[0,:]

array([0, 1, 2, 3])

In [111]:
a2[:,2]

array([ 2,  6, 10])

In [112]:
a2[2,:]

array([ 8,  9, 10, 11])

In [114]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [115]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [116]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [127]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [128]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
a3[1,0:3]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [142]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [143]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [147]:
a3[0,1,:]

array([3, 4, 5])

In [148]:
a3[1,:,1]

array([10, 13, 16])

In [150]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [152]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [153]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [157]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [158]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [159]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [160]:
#traspose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [165]:
a2.T #2method

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [166]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [167]:
a3.ravel() #convert in 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [172]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [173]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [174]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [175]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [176]:
#horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [178]:
#vertical splitting
np.hsplit(a4,5)  #error

ValueError: array split does not result in an equal division

In [179]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]